wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .my-domain.com
  power_save_mode: none

  ap:
    ssid: "Fallback AP"
    password: !secret wifi_fallback_password

captive_portal:

logger:
  level: INFO

ota:
  password: !secret ota_password

api:
  password: !secret api_password

web_server:
  port: 80


esphome:
  name: "nebula"

packages:
  platform: !include platform_bk72xx.yaml
  nebula: !include
    file: nebula_light_device.yaml
    vars:
      device_name: "Star Projector"
